"""add user password column

Revision ID: 50720ed03836
Revises: 8fb5b9e35e16
Create Date: 2016-03-29 10:47:08.078000

"""

# revision identifiers, used by Alembic.
revision = '50720ed03836'
down_revision = '8fb5b9e35e16'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=128), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    ### end Alembic commands ###
