"""add confirmed column

Revision ID: e43e597101fe
Revises: b58162422a4e
Create Date: 2016-03-31 16:17:15.147000

"""

# revision identifiers, used by Alembic.
revision = 'e43e597101fe'
down_revision = 'b58162422a4e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(create_constraint=128), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
